[package]
name = "driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
esp-hal = { version = "0.17.0", features = ["esp32"] }
esp-println = "0.9.1"
embedded-hal = "1.0.0"